NUMBER_OF_CELL =    24
NUMBER_OF_CARDS =   24

FREE_PLACE =        0
RABBIT_PLAYER_1 =   1
RABBIT_PLAYER_2 =   2
HOLE =              3

SYMBOL_CELL = {
    FREE_PLACE: "_",
    RABBIT_PLAYER_1: "R1",
    RABBIT_PLAYER_2: "R2",
    HOLE: "O"
}

ERROR = -1
MOVING_1 =      1
MOVING_2 =      2
MOVING_3 =      3
MOVING_CARROT = 4

ORIGINAL_LIST_CARDS = []
